set -e
true
true
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-hammer /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/corrected/configs/config.info
/opt/anaconda3/envs/miseq/bin/python3 /Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/corrected/corrected.yaml --ext_python_modules_home /Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/share/spades --max_threads 16 --output_dir /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/corrected --gzip_output
true
true
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K21/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K33/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K55/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K77/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K99/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/configs/config.info
/opt/anaconda3/envs/miseq/bin/python3 /Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/share/spades/spades_pipeline/scripts/copy_files.py /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/before_rr.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/before_rr.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/assembly_graph_after_simplification.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/assembly_graph_after_simplification.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/final_contigs.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/contigs.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/first_pe_contigs.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/first_pe_contigs.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/strain_graph.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/strain_graph.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/scaffolds.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/scaffolds.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/scaffolds.paths /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/scaffolds.paths /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/assembly_graph_with_scaffolds.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/assembly_graph_with_scaffolds.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/assembly_graph.fastg /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/assembly_graph.fastg /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/K127/final_contigs.paths /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/contigs.paths
true
/opt/anaconda3/envs/miseq/bin/python3 /Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/scaffolds.fasta --misc_dir /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta2/misc --threshold_for_breaking_scaffolds 3
true
