set -e
true
true
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-hammer /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/corrected/configs/config.info
/opt/anaconda3/bin/python3 /Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/share/spades/spades_pipeline/scripts/compress_all.py --input_file /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/corrected/corrected.yaml --ext_python_modules_home /Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/share/spades --max_threads 16 --output_dir /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/corrected --gzip_output
true
true
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K21/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K33/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K55/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K77/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K99/configs/config.info
/Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/bin/spades-core /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/configs/config.info
/opt/anaconda3/bin/python3 /Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/share/spades/spades_pipeline/scripts/copy_files.py /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/before_rr.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/before_rr.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/assembly_graph_after_simplification.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/assembly_graph_after_simplification.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/final_contigs.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/contigs.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/first_pe_contigs.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/first_pe_contigs.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/strain_graph.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/strain_graph.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/scaffolds.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/scaffolds.fasta /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/scaffolds.paths /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/scaffolds.paths /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/assembly_graph_with_scaffolds.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/assembly_graph_with_scaffolds.gfa /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/assembly_graph.fastg /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/assembly_graph.fastg /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/K127/final_contigs.paths /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/contigs.paths
true
/opt/anaconda3/bin/python3 /Users/samklauer/Downloads/SPAdes-4.0.0-Darwin/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/scaffolds.fasta --misc_dir /Users/samklauer/GitHub/PawseySummer2024/metagenome/mockmeta/misc --threshold_for_breaking_scaffolds 3
true
